# Generated by Django 4.0.4 on 2022-05-22 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Подраздел')),
            ],
            options={
                'verbose_name': 'Подраздел',
                'verbose_name_plural': 'Подразделы',
            },
        ),
        migrations.CreateModel(
            name='Shortcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default.html', max_length=100, verbose_name='Шорткод')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.category', verbose_name='Раздел')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.subcategory', verbose_name='Подраздел')),
            ],
            options={
                'verbose_name': 'Шорткод',
                'verbose_name_plural': 'Шорткоды',
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='ИНН')),
                ('ogrn', models.IntegerField(validators=[django.core.validators.MinValueValidator(13)], verbose_name='ОГРН')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('city', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('index', models.IntegerField(validators=[django.core.validators.MinValueValidator(6)], verbose_name='Индекс')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
                ('heading', models.CharField(max_length=100, verbose_name='Рубрика')),
                ('keywords', models.CharField(blank=True, max_length=100, verbose_name='Ключевые слова')),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(11)], verbose_name='Телефон')),
                ('cell_phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(11)], verbose_name='Сотовый телефон')),
                ('metro', models.CharField(blank=True, max_length=100, verbose_name='Метро(остановка)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('site', models.CharField(max_length=100, verbose_name='Сайт')),
                ('vk', models.CharField(max_length=100, verbose_name='Vk')),
                ('twtr', models.CharField(max_length=100, verbose_name='Twitter')),
                ('fb', models.CharField(max_length=100, verbose_name='Facebook')),
                ('inst', models.CharField(max_length=100, verbose_name='Instagram')),
                ('x', models.FloatField(help_text='xx.xxxxxx', max_length=8, validators=[django.core.validators.MinValueValidator(8)], verbose_name='X')),
                ('y', models.FloatField(help_text='xx.xxxxxx', max_length=8, validators=[django.core.validators.MinValueValidator(8)], verbose_name='Y')),
                ('additional', models.TextField(blank=True, help_text='Дополнительная информация', verbose_name='Дополнительно')),
                ('work_time', models.CharField(max_length=50, verbose_name='Время работы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.category', verbose_name='Раздел')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.subcategory', verbose_name='Подраздел')),
            ],
            options={
                'verbose_name': 'Конструктор',
                'verbose_name_plural': 'Конструкторы',
            },
        ),
    ]
